Check if deployed branch is the main branch to avoid errors of 'already checkedout'

diff --git a/wordpress-deploy/app-release b/wordpress-deploy/app-release
--- a/wordpress-deploy/app-release
+++ b/wordpress-deploy/app-release
@@ -129,8 +129,23 @@ if [ "$B" == "$*" ]; then
     fi
 elif [ "$B" != "false" ]; then
     git fetch origin
-    echo "$B"
-    git checkout -b "$B" "origin/$B"
+
+    # Check if git fetch was successful
+    if [ $? -eq 0 ]; then
+        echo "$B"
+
+        # Get current branch
+        current_branch=$(git rev-parse --abbrev-ref HEAD)
+
+        # Check if the current branch is different from $B
+        if [ "$current_branch" != "$B" ]; then
+            git checkout -b "$B" "origin/$B"
+        else
+            echo "Already on branch $B. Skipping checkout."
+        fi
+    else
+        echo "Failed to fetch from origin. Aborting."
+    fi
 fi
 
 # Make symbolic link for uploads directory
